alias gs="git status"
alias gd="git diff"
alias gdc="git diff --cached"
alias gl="git log"
alias gb="git branch"
alias gc="git checkout"
alias gmm='git merge master'
alias gy="git pull"
alias gyum='git pull upstream master'
alias gau='git add $(git ls-files -o --exclude-standard)'
alias git-root="git rev-parse --show-toplevel"
